### ISSUE TITLE
blueprint error

### ISSUE THREAD

**Issue by lihaiecnu** [oculus-samples/Unreal-MRUtilityKitSample#1]
These errors appear in the blueprint. I want to know which engine version and plug-in version this project is for. （I use version 5.4.1 forked now）

![image](https://github.com/user-attachments/assets/83ba46d7-2df8-4270-81c7-14bd761ed64f)

**Comment by felixweilbach** [comment]
This sample is targeted at Unreal Engine 5.4 and the latest version of the MetaXR SDK which at this point is v67. You can down load it here https://developer.oculus.com/downloads/package/unreal-5-platform-sdk-plugin

Please keep in mind that the MRUK plugin has been moved into the MetaXR plugin starting from v67. Please make sure that you don't have the standalone plugin of MRUK installed when you use the v67 version of the MetaXR plugin.

**Comment by felixweilbach** [comment]
As this looks not like an issue with MRUK I will close this ticket. If you feel like there is still an issue feel free to open the ticket again.
