### ISSUE TITLE
New MRUK sample for Unreal MetaXR v67

### ISSUE THREAD

**Issue by Junnn424** [oculus-samples/Unreal-MRUtilityKitSample#2]
Hi! As the new MetaXR plugin came out, in the document it says that the MRUK feature is now being moved into MetaXR plugin. 
However it seems the current MRUK sample project is still in UE5.3, does this means the sample is still using v65 SDK?
Would there be a MRUK sample project in 5.4 using just the MetaXR plugin?
We had a project in 5.3 that uses MRUK, as we upgrade to UE5.4 we start to have some package error-- not sure if those are related to MRUK, but do you think there might be any issue for upgrading a MRUK projec to v67 SDK?

Thank you!

**Comment by Junnn424** [comment]
Hi @MartinSherburn ,
Thank you so much for getting back on this!
We did figure out the package error in UE54 and had several successful package using MetaXR v67 with MRUK features.
However we noticed a significant quality drop with the actor spawning, almost 95% of the time some walls are missing or spawned at wrong place, while the same room scan works just fine in older version. Here is a recording for your reference, the MRUtilityKit Sample project is UE5.4 + MetaXR v.67 and the "Perfomer" app is UE5.3 + MetaXR 64 + MRUK v64:
https://youtube.com/shorts/f0J2bX60GBs?feature=share

Hopefully it's already under the list in the next update! We would really love to upgrade to v67 to use the much optimized Depth Occlusion but some of these bugs are making us worried.

A couple more things that we found:
- Depth Occlusion works perfect at the first level, but once we travel to a nother map it starts to render differently on each eye (see pic reference below)
recording: https://youtu.be/by_Wx87PESo
![2024-08-06T02-52-49 395Z](https://github.com/user-attachments/assets/e4720865-783b-47ff-8e0f-6abb3c4e1f76)

- APK crash if there's a "None" under BP_AnchorActorSpawner's actor list when populating the scene.
![Screenshot 2024-08-05 154655](https://github.com/user-attachments/assets/b7db1543-1d9a-4bb4-b528-f076b77fc9b2)

**Comment by felixweilbach** [comment]
Hi @Junnn424,

thanks for the detailed description.

The issues with actor spawning have been discovered internally already and we have fix for it. It will be fixed in the next release.

I will forward the occlusion issue to the team that works on occlusions.

For the crash I think we should prevent that, however if you do not want to spawn any actor remove it from the list instead of specifying None.

**Comment by Junnn424** [comment]
Thank you @felixweilbach ! Glad to know it's already been taken care of, and thank you so much for the quick response!
For the crash issue, that's indeed what we do-- we cleaned out the "None" from the list and it's running fine ever since. Just mention it because the "None" causing crash issue is also a new thing in v.67, we upgraded from v.65+UE53 and was not having the crash even though we have several "None" in the list.
Thanks again for forwarding the issues!

**Comment by Junnn424** [comment]
Hi @MartinSherburn ,
Sure, I'll create a new ticket there and respond there!

**Comment by MartinSherburn** [comment]
> However we noticed a significant quality drop with the actor spawning, almost 95% of the time some walls are missing or spawned at wrong place, while the same room scan works just fine in older version.

@Junnn424 I created a PR which you can pull into your own repository to fix the Scene Loading issue. Please take a look here:

https://github.com/Oculus-VR/UnrealEngine/pull/490

As @felixweilbach mentioned this will be fixed in v69.
