### ISSUE TITLE
Is there a way to have world lock on for host and off for client?  

### ISSUE THREAD

**Issue by gabryelx** [oculus-samples/Unreal-MRUtilityKitSample#8]
I'm looking at having a remote player join a host player (P2P) in their MR space (a mapped room with procedural meshes), but as a VR pawn with VR locomotion.  It seems to me to accomplish this, world lock would only be relevant for the host player, however it seems to be a project level setting currently.  Is there control over this?  

Thanks

**Comment by felixweilbach** [comment]
I forwarded your request to the relevant developer.

**Comment by gabryelx** [comment]
Thank you for this clarification, that makes sense but wasn't immediately obvious.  I assumed World Lock was a global setting designed for local Colocation and enforced on both host and client.  Cheers!
